kind: pipeline
type: docker
name: build

steps:
- name: restore ASDF cache
  image: meltwater/drone-cache
  pull: true
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: SECRET_ACCESS_KEY
    AWS_PLUGIN_PATH_STYLE: true
  settings:
    restore: true
    endpoint:
      from_secret: S3_ENDPOINT
    bucket:
      from_secret: CACHE_BUCKET
    region: us-east-1
    path-style: true
    cache_key: 'asdf-{{ checksum ".tool-versions" }}'
    mount:
    - .asdf

- name: restore build cache
  image: meltwater/drone-cache
  pull: true
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: SECRET_ACCESS_KEY
    AWS_PLUGIN_PATH_STYLE: true
  settings:
    restore: true
    endpoint:
      from_secret: S3_ENDPOINT
    bucket:
      from_secret: CACHE_BUCKET
    region: us-east-1
    path-style: true
    cache_key: 'elixir-{{ checksum "mix.lock" }}'
    mount:
    - deps
    - _build
    - .hex
    - .mix

- name: install dependencies
  image: code.harton.nz/james/asdf_container:latest
  pull: true
  environment:
    MIX_ENV: test
    HEX_HOME: /drone/src/.hex
    MIX_HOME: /drone/src/.mix
    ASDF_DATA_DIR: /drone/src/.asdf
  depends_on:
  - restore ASDF cache
  - restore build cache
  commands:
  - asdf_install
  - rm -rf .asdf/downloads
  - ASDF_DIR=~/.asdf
  - . $ASDF_DIR/asdf.sh
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - mix deps.compile

- name: store ASDF cache
  image: meltwater/drone-cache
  pull: true
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: SECRET_ACCESS_KEY
    AWS_PLUGIN_PATH_STYLE: true
  depends_on:
  - install dependencies
  settings:
    rebuild: true
    endpoint:
      from_secret: S3_ENDPOINT
    bucket:
      from_secret: CACHE_BUCKET
    region: us-east-1
    path-style: true
    cache_key: 'asdf-{{ checksum ".tool-versions" }}'
    mount:
    - .asdf

- name: store build cache
  image: meltwater/drone-cache
  pull: true
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: SECRET_ACCESS_KEY
    AWS_PLUGIN_PATH_STYLE: true
  depends_on:
  - install dependencies
  settings:
    rebuild: true
    endpoint:
      from_secret: S3_ENDPOINT
    bucket:
      from_secret: CACHE_BUCKET
    region: us-east-1
    path-style: true
    cache_key: 'elixir-{{ checksum "mix.lock" }}'
    mount:
    - deps
    - _build
    - .hex
    - .mix

---

kind: pipeline
type: docker
name: test

depends_on:
  - build

steps:
- name: restore ASDF cache
  image: meltwater/drone-cache
  pull: true
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: SECRET_ACCESS_KEY
    AWS_PLUGIN_PATH_STYLE: true
  settings:
    restore: true
    endpoint:
      from_secret: S3_ENDPOINT
    bucket:
      from_secret: CACHE_BUCKET
    region: us-east-1
    path-style: true
    cache_key: 'asdf-{{ checksum ".tool-versions" }}'
    mount:
    - .asdf

- name: restore build cache
  image: meltwater/drone-cache
  pull: true
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: SECRET_ACCESS_KEY
    AWS_PLUGIN_PATH_STYLE: true
  settings:
    restore: true
    endpoint:
      from_secret: S3_ENDPOINT
    bucket:
      from_secret: CACHE_BUCKET
    region: us-east-1
    path-style: true
    cache_key: 'elixir-{{ checksum "mix.lock" }}'
    mount:
    - deps
    - _build
    - .hex
    - .mix

- name: mix compile
  image: code.harton.nz/james/asdf_container:latest
  pull: true
  environment:
    MIX_ENV: test
    HEX_HOME: /drone/src/.hex
    MIX_HOME: /drone/src/.mix
    ASDF_DATA_DIR: /drone/src/.asdf
  depends_on:
  - restore ASDF cache
  - restore build cache
  commands:
  - asdf mix compile --warnings-as-errors

- name: mix test
  image: code.harton.nz/james/asdf_container:latest
  pull: true
  environment:
    MIX_ENV: test
    HEX_HOME: /drone/src/.hex
    MIX_HOME: /drone/src/.mix
    ASDF_DATA_DIR: /drone/src/.asdf
  depends_on:
  - mix compile
  commands:
  - asdf mix test

- name: mix credo
  image: code.harton.nz/james/asdf_container:latest
  pull: true
  environment:
    MIX_ENV: test
    HEX_HOME: /drone/src/.hex
    MIX_HOME: /drone/src/.mix
    ASDF_DATA_DIR: /drone/src/.asdf
  depends_on:
  - mix compile
  commands:
  - asdf mix credo --strict

- name: mix sobelow
  image: code.harton.nz/james/asdf_container:latest
  pull: true
  environment:
    MIX_ENV: test
    HEX_HOME: /drone/src/.hex
    MIX_HOME: /drone/src/.mix
    ASDF_DATA_DIR: /drone/src/.asdf
  depends_on:
  - mix compile
  commands:
  - asdf mix sobelow --skip

- name: mix hex.audit
  image: code.harton.nz/james/asdf_container:latest
  pull: true
  environment:
    MIX_ENV: test
    HEX_HOME: /drone/src/.hex
    MIX_HOME: /drone/src/.mix
    ASDF_DATA_DIR: /drone/src/.asdf
  depends_on:
  - mix compile
  commands:
  - asdf mix hex.audit

- name: mix format
  image: code.harton.nz/james/asdf_container:latest
  pull: true
  environment:
    MIX_ENV: test
    HEX_HOME: /drone/src/.hex
    MIX_HOME: /drone/src/.mix
    ASDF_DATA_DIR: /drone/src/.asdf
  depends_on:
  - mix compile
  commands:
  - asdf mix format --check-formatted

- name: mix spark.formatter
  image: code.harton.nz/james/asdf_container:latest
  pull: true
  environment:
    MIX_ENV: test
    HEX_HOME: /drone/src/.hex
    MIX_HOME: /drone/src/.mix
    ASDF_DATA_DIR: /drone/src/.asdf
  depends_on:
  - mix compile
  commands:
  - asdf mix spark.formatter --check

- name: mix deps.unlock
  image: code.harton.nz/james/asdf_container:latest
  pull: true
  environment:
    MIX_ENV: test
    HEX_HOME: /drone/src/.hex
    MIX_HOME: /drone/src/.mix
    ASDF_DATA_DIR: /drone/src/.asdf
  depends_on:
  - mix compile
  commands:
  - asdf mix deps.unlock --check-unused

- name: mix doctor
  image: code.harton.nz/james/asdf_container:latest
  pull: true
  environment:
    MIX_ENV: test
    HEX_HOME: /drone/src/.hex
    MIX_HOME: /drone/src/.mix
    ASDF_DATA_DIR: /drone/src/.asdf
  depends_on:
  - mix compile
  commands:
  - asdf mix doctor --full

- name: mix git_ops.check_message
  image: code.harton.nz/james/asdf_container:latest
  pull: true
  environment:
    MIX_ENV: test
    HEX_HOME: /drone/src/.hex
    MIX_HOME: /drone/src/.mix
    ASDF_DATA_DIR: /drone/src/.asdf
  depends_on:
  - mix compile
  commands:
  - git log -1 --format=%s > .last_commit_message
  - asdf mix git_ops.check_message .last_commit_message

---
kind: pipeline
type: docker
name: release

triggers:
  branch:
  - main
  - add-drone-ci-config

depends_on:
  - test

steps:
- name: restore ASDF cache
  image: meltwater/drone-cache
  pull: true
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: SECRET_ACCESS_KEY
    AWS_PLUGIN_PATH_STYLE: true
  settings:
    restore: true
    endpoint:
      from_secret: S3_ENDPOINT
    bucket:
      from_secret: CACHE_BUCKET
    region: us-east-1
    path-style: true
    cache_key: 'asdf-{{ checksum ".tool-versions" }}'
    mount:
    - .asdf

- name: restore build cache
  image: meltwater/drone-cache
  pull: true
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: SECRET_ACCESS_KEY
    AWS_PLUGIN_PATH_STYLE: true
  settings:
    restore: true
    endpoint:
      from_secret: S3_ENDPOINT
    bucket:
      from_secret: CACHE_BUCKET
    region: us-east-1
    path-style: true
    cache_key: 'elixir-{{ checksum "mix.lock" }}'
    mount:
    - deps
    - _build
    - .hex
    - .mix

- name: attempt git_ops release
  image: code.harton.nz/james/asdf_container:latest
  pull: true
  depends_on:
  - restore ASDF cache
  - restore build cache
  environment:
    MIX_ENV: test
    HEX_HOME: /drone/src/.hex
    MIX_HOME: /drone/src/.mix
    ASDF_DATA_DIR: /drone/src/.asdf
  commands:
  - |
    export ASDF_DIR=~/.asdf
    . $ASDF_DIR/asdf.sh
    mix git_ops.project_info --format=shell > before.env
    mix git_ops.release --yes --no-major || true
    mix git_ops.project_info --format=shell > after.env
    . ./before.env
    export OLD_APP_VERSION=$APP_VERSION
    . ./after.env
    if [ "v${OLD_APP_VERSION}" != "v${APP_VERSION}" ]; then
      mix esbuild prod
      mix hex.build -o "artifacts/${APP_NAME}-${APP_VERSION}.tar"
      gzip "artifacts/${APP_NAME}-${APP_VERSION}.tar"
      mix docs && tar zcvf "artifacts/${APP_NAME}-${APP_VERSION}-docs.tar.gz" doc/
      git push $DRONE_GIT_HTTP_URL "HEAD:${DRONE_COMMIT_REF}" "refs/tags/v${APP_VERSION}"
    fi
