kind: pipeline
type: docker
name: build

steps:
- name: restore cache
  image: meltwater/drone-cache
  pull: true
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: SECRET_ACCESS_KEY
    AWS_PLUGIN_PATH_STYLE: true
  settings:
    restore: true
    endpoint:
      from_secret: S3_ENDPOINT
    bucket:
      from_secret: CACHE_BUCKET
    region: us-east-1
    path-style: true
    mount:
    - .asdf
    - deps
    - _build
    - .hex
    - .mix

- name: install dependencies
  image: code.harton.nz/james/asdf_container:latest
  environment:
    MIX_ENV: test
    HEX_HOME: /drone/src/.hex
    MIX_HOME: /drone/src/.mix
    ASDF_DATA_DIR: /drone/src/.asdf
  commands:
   - asdf_install
   - asdf mix local.hex --force
   - asdf mix local.rebar --force
   - asdf mix deps.get
   - asdf mix deps.compile

- name: store cache
  image: meltwater/drone-cache
  pull: true
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: SECRET_ACCESS_KEY
    AWS_PLUGIN_PATH_STYLE: true
  settings:
    rebuild: true
    endpoint:
      from_secret: S3_ENDPOINT
    bucket:
      from_secret: CACHE_BUCKET
    region: us-east-1
    path-style: true
    mount:
    - .asdf
    - deps
    - _build
    - .hex
    - .mix
