kind: pipeline
type: docker
name: build

steps:
- name: restore cache
  image: drillster/drone-volume-cache
  environment:
    MIX_ENV: test
    HEX_HOME: "$DRONE_WORKSPACE/.hex"
    MIX_HOME: "$DRONE_WORKSPACE/.mix"
  volumes: 
  - name: cache
    path: /cache
  settings:
    restore: true
    mount:
    - $HOME/.asdf
    - $DRONE_WORKSPACE/deps
    - $DRONE_WORKSPACE/_build
    - $DRONE_WORKSPACE/.hex
    - $DRONE_WORKSPACE/.mix
- name: install dependencies
  image: code.harton.nz/james/asdf_container:latest
  commands:
   - asdf_install
   - asdf mix local.hex --force
   - asdf mix local.rebar --force
   - asdf mix deps.get
   - asdf mix deps.compile


volumes:
- name: cache
  host:
    path: /tmp/cache/$DRONE_REPO/
